version: '3'
services:
  service-debug:
    build: app
    container_name: service-debug
    expose:
      - "8000"
    command: >
      bash -c "pip install django-extensions django-cors-headers && bash run_uwsgi.sh"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DEBUG=True
      - PERMISSION_REQUIRED=
    volumes:
      - ./data/static:/opt/app/static
      - ./fixtures:/opt/app/fixtures

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/swagger.yaml
    volumes:
      - ./openapi.yaml:/swagger.yaml

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service-debug
    links:
      - service-debug:service
    ports:
      - "80:80"

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
